spring:
  cloud:
    stream:
      bindings:
        output:
          destination: sample-topic  # Kafka topic name for output
          content-type: application/json
        input:
          destination: sample-topic  # Kafka topic name for input
          group: sample-group  # Kafka consumer group
          content-type: application/json

  kafka:
    binder:
      brokers: localhost:9092  # Replace with your Kafka broker address
      auto-create-topics: true

  server:
    port: 8080
